import { Ban, History, MessageSquareText, Tag, Users } from "lucide-react";
import type { OwnerUserDetail } from "../types";
import type { DrawerTab } from "./types";
export function UserDrawerContent(props: { detail: OwnerUserDetail; tab: DrawerTab; saving: boolean; can(permission: string): boolean; formatDate(value?: string | null): string; onRemoveTag(tag: string): void }) {
  const { detail, tab } = props;
  return <div className="owner-user-drawer__body">
    {tab === "overview" ? <div className="owner-user-detail-grid"><article><small>Telegram ID</small><strong>{detail.telegram_id}</strong></article><article><small>Рівень</small><strong>{detail.global_level}</strong></article><article><small>Реєстрація</small><strong>{props.formatDate(detail.created_at)}</strong></article><article><small>Остання активність</small><strong>{props.formatDate(detail.last_activity_at)}</strong></article>{detail.is_blocked ? <section className="owner-user-warning"><Ban size={18} /><div><strong>Повний блок</strong><p>{detail.restriction?.reason || "Причину не вказано"}</p></div></section> : null}<section className="owner-user-note-card"><div><MessageSquareText size={16} /><strong>Приватна нотатка</strong></div><p>{detail.note || "Нотатки ще немає."}</p></section><section className="owner-user-tag-card"><div><Tag size={16} /><strong>Теги</strong></div><div className="owner-user-tags">{detail.tags.length ? detail.tags.map((item) => <button key={item} type="button" disabled={!props.can("users.notes") || props.saving} onClick={() => props.onRemoveTag(item)}>#{item} ×</button>) : <span>Немає тегів</span>}</div></section></div> : null}
    {tab === "groups" ? <div className="owner-user-history-list">{detail.groups.length ? detail.groups.map((group) => <article key={group.telegram_chat_id}><Users size={17} /><div><strong>{group.title}</strong><small>{group.xp_total} XP · рівень {group.level}</small></div><time>{props.formatDate(group.last_seen_at)}</time></article>) : <div className="owner-empty">Користувач поки не входить до груп.</div>}</div> : null}
    {tab === "payments" ? <div className="owner-user-payment-summary"><article><small>Усього Stars</small><strong>{detail.payment_summary.stars_total.toLocaleString("uk-UA")} ⭐</strong></article><article><small>Успішних оплат</small><strong>{detail.payment_summary.payment_count}</strong></article><article><small>Остання оплата</small><strong>{props.formatDate(detail.payment_summary.last_payment_at)}</strong></article><article><small>Підписка</small><strong>{detail.payment_summary.active_subscription ? "Активна" : "Немає"}</strong></article></div> : null}
    {tab === "history" ? <div className="owner-user-history-list">{detail.audit.length ? detail.audit.map((item) => <article key={item.id}><History size={17} /><div><strong>{item.action}</strong><small>Actor ID {item.actor_telegram_user_id}</small></div><time>{props.formatDate(item.created_at)}</time></article>) : <div className="owner-empty">Історія змін порожня.</div>}</div> : null}
  </div>;
}
