import { useMemo, useState } from "react";
import { X } from "lucide-react";
import { ownerApi } from "../ownerApi";
import type { OwnerUserDetail, StaffRole } from "../types";
import type { UserAction } from "./types";
export function UserActionSheet({ action, detail, saving, onClose, onRun }: { action: Exclude<UserAction, null>; detail: OwnerUserDetail; saving: boolean; onClose(): void; onRun(task: () => Promise<unknown>): void }) {
  const [reason, setReason] = useState(""); const [amount, setAmount] = useState("0"); const [groupId, setGroupId] = useState(""); const [message, setMessage] = useState(""); const [note, setNote] = useState(detail.note); const [tag, setTag] = useState(""); const [role, setRole] = useState<StaffRole>("support"); const [vipMode, setVipMode] = useState<"permanent" | "until">("permanent"); const [vipDate, setVipDate] = useState("");
  const minimumDate = useMemo(() => new Date(Date.now() + 86_400_000).toISOString().slice(0, 10), []);
  const title = action === "vip" ? "Керування VIP" : action === "block" ? "Керування доступом" : action === "xp" ? "Зміна XP" : action === "role" ? "Роль команди" : action === "note" ? "Приватна нотатка" : action === "tag" ? "Новий тег" : "Повідомлення від бота";
  const submit = () => { if (action === "vip") { if (detail.vip.is_active) onRun(() => ownerApi.revokeVip(detail.telegram_id, { reason, confirmation: "ВІДКЛИКАТИ VIP" })); else onRun(() => ownerApi.grantVip(detail.telegram_id, { mode: vipMode, ...(vipMode === "until" && vipDate ? { expires_at: new Date(`${vipDate}T23:59:59Z`).toISOString() } : {}), reason, confirmation: "ВИДАТИ VIP" })); } else if (action === "block") onRun(() => detail.is_blocked ? ownerApi.unblockUser(detail.telegram_id, reason) : ownerApi.blockUser(detail.telegram_id, reason)); else if (action === "xp") onRun(() => ownerApi.adjustXp(detail.telegram_id, Number(amount), reason, groupId ? Number(groupId) : undefined)); else if (action === "role") onRun(() => ownerApi.setRole(detail.telegram_id, role)); else if (action === "note") onRun(() => ownerApi.saveNote(detail.telegram_id, note)); else if (action === "tag") onRun(() => ownerApi.addTag(detail.telegram_id, tag)); else onRun(() => ownerApi.messageUser(detail.telegram_id, message)); };
  return <section className="owner-user-action-sheet"><header><strong>{title}</strong><button type="button" onClick={onClose}><X size={17} /></button></header>{action === "vip" && !detail.vip.is_active ? <div className="owner-action-choice"><button type="button" className={vipMode === "permanent" ? "is-active" : ""} onClick={() => setVipMode("permanent")}>Безстроково</button><button type="button" className={vipMode === "until" ? "is-active" : ""} onClick={() => setVipMode("until")}>До дати</button></div> : null}{action === "vip" && !detail.vip.is_active && vipMode === "until" ? <input type="date" min={minimumDate} value={vipDate} onChange={(event) => setVipDate(event.target.value)} /> : null}{action === "xp" ? <><input type="number" min={-100000} max={100000} value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Наприклад: 100 або -50" /><select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">Глобальний XP</option>{detail.groups.map((group) => <option key={group.telegram_chat_id} value={group.telegram_chat_id}>{group.title}</option>)}</select></> : null}{action === "role" ? <select value={role} onChange={(event) => setRole(event.target.value as StaffRole)}><option value="support">Support</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select> : null}{action === "note" ? <textarea value={note} maxLength={4000} onChange={(event) => setNote(event.target.value)} placeholder="Внутрішня нотатка для команди" /> : null}{action === "tag" ? <input value={tag} maxLength={32} onChange={(event) => setTag(event.target.value)} placeholder="Наприклад: тестер" /> : null}{action === "message" ? <textarea value={message} maxLength={1000} onChange={(event) => setMessage(event.target.value)} placeholder="Текст приватного повідомлення" /> : null}{(["vip", "block", "xp"] as UserAction[]).includes(action) ? <textarea value={reason} maxLength={500} onChange={(event) => setReason(event.target.value)} placeholder="Обов’язкова причина" /> : null}<div className="owner-user-action-buttons">{action === "role" && detail.role && detail.role !== "owner" ? <button type="button" className="is-danger" disabled={saving || reason.trim().length < 3} onClick={() => onRun(() => ownerApi.removeRole(detail.telegram_id, reason))}>Зняти роль</button> : null}<button type="button" disabled={saving} onClick={submit}>{saving ? "Зберігаю…" : action === "block" ? (detail.is_blocked ? "Розблокувати" : "Повністю заблокувати") : action === "message" ? "Надіслати" : "Підтвердити"}</button></div></section>;
}
