create table if not exists public.vip_product_events (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    event_type varchar(48) not null,
    source varchar(64) not null,
    feature_key varchar(96),
    metadata_json text not null default '{}',
    created_at timestamptz not null default now()
);

create index if not exists ix_vip_product_event_created
    on public.vip_product_events (created_at);
create index if not exists ix_vip_product_event_user_created
    on public.vip_product_events (telegram_user_id, created_at);
create index if not exists ix_vip_product_event_type_source
    on public.vip_product_events (event_type, source);

alter table public.vip_product_events enable row level security;
revoke all on table public.vip_product_events from anon, authenticated;
revoke all on sequence public.vip_product_events_id_seq from anon, authenticated;
