create table if not exists public.owner_payment_notes (
    id bigint generated by default as identity primary key,
    owner_telegram_user_id bigint not null,
    payment_id bigint not null references public.vip_payments(id) on delete cascade,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    note_text text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_owner_payment_note_payment unique (payment_id)
);

alter table public.owner_payment_notes enable row level security;
revoke all on table public.owner_payment_notes from anon, authenticated;
revoke all on sequence public.owner_payment_notes_id_seq from anon, authenticated;
