begin;

create table if not exists public.vip_invoice_intents (
    id bigint generated by default as identity primary key,
    payload varchar(128) not null unique,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    product_code varchar(32) not null,
    stars_amount integer not null check (stars_amount > 0),
    is_recurring boolean not null default false,
    status varchar(24) not null default 'open',
    created_at timestamptz not null default now(),
    invalidated_at timestamptz null
);

create index if not exists ix_vip_invoice_user_created
    on public.vip_invoice_intents (telegram_user_id, created_at desc);

create table if not exists public.vip_payments (
    id bigint generated by default as identity primary key,
    invoice_intent_id bigint not null references public.vip_invoice_intents(id) on delete restrict,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    product_code varchar(32) not null,
    stars_amount integer not null check (stars_amount > 0),
    telegram_payment_charge_id varchar(255) not null,
    provider_payment_charge_id varchar(255) null,
    is_recurring boolean not null default false,
    is_first_recurring boolean not null default false,
    subscription_expiration_date timestamptz null,
    granted_until timestamptz null,
    status varchar(24) not null default 'paid',
    paid_at timestamptz not null default now(),
    refunded_at timestamptz null,
    refund_reason varchar(255) null,
    constraint uq_vip_payment_telegram_charge unique (telegram_payment_charge_id)
);

create index if not exists ix_vip_payment_user_paid
    on public.vip_payments (telegram_user_id, paid_at desc);
create index if not exists ix_vip_payment_invoice
    on public.vip_payments (invoice_intent_id, paid_at desc);

create table if not exists public.vip_trial_claims (
    telegram_user_id bigint primary key references public.users(telegram_id) on delete cascade,
    payment_id bigint not null unique references public.vip_payments(id) on delete restrict,
    claimed_at timestamptz not null default now()
);

create table if not exists public.vip_notifications (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    notification_key varchar(160) not null,
    created_at timestamptz not null default now(),
    constraint uq_vip_notification_once unique (telegram_user_id, notification_key)
);

create index if not exists ix_vip_notification_created
    on public.vip_notifications (created_at desc);

alter table public.vip_invoice_intents enable row level security;
alter table public.vip_payments enable row level security;
alter table public.vip_trial_claims enable row level security;
alter table public.vip_notifications enable row level security;

revoke all on table public.vip_invoice_intents from anon, authenticated;
revoke all on table public.vip_payments from anon, authenticated;
revoke all on table public.vip_trial_claims from anon, authenticated;
revoke all on table public.vip_notifications from anon, authenticated;

commit;
