create table if not exists public.engagement_profiles (
    telegram_user_id bigint primary key references public.users(telegram_id) on delete cascade,
    private_started_at timestamptz,
    onboarding_completed_at timestamptz,
    last_retention_sent_at timestamptz,
    last_retention_type varchar(48),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.onboarding_group_links (
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    telegram_chat_id bigint not null references public.chat_groups(telegram_chat_id) on delete cascade,
    bot_status varchar(32) not null default 'member',
    connected_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (telegram_user_id, telegram_chat_id)
);

create index if not exists ix_onboarding_group_links_chat
    on public.onboarding_group_links (telegram_chat_id);

create table if not exists public.engagement_notifications (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    telegram_chat_id bigint,
    notification_type varchar(48) not null,
    notification_key varchar(180) not null,
    status varchar(24) not null default 'claimed',
    claimed_at timestamptz not null default now(),
    sent_at timestamptz,
    constraint uq_engagement_notification_user_key
        unique (telegram_user_id, notification_key)
);

create index if not exists ix_engagement_notifications_sent
    on public.engagement_notifications (sent_at);
create index if not exists ix_engagement_notifications_type
    on public.engagement_notifications (notification_type, claimed_at);

create table if not exists public.engagement_rank_snapshots (
    telegram_user_id bigint not null references public.users(telegram_id) on delete cascade,
    telegram_chat_id bigint not null references public.chat_groups(telegram_chat_id) on delete cascade,
    rank integer not null check (rank > 0),
    period_start date not null,
    updated_at timestamptz not null default now(),
    primary key (telegram_user_id, telegram_chat_id)
);

alter table public.engagement_profiles enable row level security;
alter table public.onboarding_group_links enable row level security;
alter table public.engagement_notifications enable row level security;
alter table public.engagement_rank_snapshots enable row level security;

comment on table public.engagement_profiles is
    'Private onboarding and retention cooldown state. Service role only.';
comment on table public.onboarding_group_links is
    'Users who connected ChatPulse to a group. Service role only.';
comment on table public.engagement_notifications is
    'Idempotency journal for private retention notifications. Service role only.';
comment on table public.engagement_rank_snapshots is
    'Weekly rank snapshots used to report real movement. Service role only.';
